name = "Gruvbox"
license = "MIT"
licenselink = "https://github.com/schnerring/hugo-theme-gruvbox-light/blob/main/LICENSE"
description = "A fork of the retro-looking hugo-theme-gruvbox"
homepage = "https://github.com/lgaida/hugo-theme-gruvbox-light"
tags = [
  "blog",
  "dark mode",
  "minimal",
  "personal",
  "responsive"
]
features = ["dark mode"]
min_version = "0.41.0"

[author]
  name = "Lenard Gaida"
  homepage = "http://lgaida.de"
